import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

function getPapersSidebar() {
  const papersDir = path.resolve(__dirname, './docs/papers');

  
  const yearFolders = fs.readdirSync(papersDir)
    .filter((folder) => folder.startsWith('RoboCup '))
    .sort((a, b) => {
      const yearA = parseInt(a.replace('RoboCup ', ''));
      const yearB = parseInt(b.replace('RoboCup ', ''));
      return yearB - yearA; 
    });

  
  const items: { type: 'doc'; id: string; label: string }[] = yearFolders.map((folder) => ({
    type: 'doc', 
    id: `papers/${folder}/index`, // ID of the document
    label: folder,
  }));

  return items;
}

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  serverManual: [{type: 'autogenerated', dirName: 'server-manual'}],
  openSourceProjects: [{type: 'autogenerated', dirName: 'open-source-projects'}],
  papers: getPapersSidebar(),
  competitions: [{type: 'autogenerated', dirName: 'competitions'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
